# Generated by Django 3.0 on 2023-09-03 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climatefinance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='item_desc',
            new_name='project_desc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='item_name',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='item_price',
            new_name='project_price',
        ),
    ]
